import { chromium } from "playwright";

const BASE = "https://cataleya-aromas.vercel.app";
const browser = await chromium.launch({ channel: "msedge" });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
ctx.setDefaultTimeout(45000);
const a = await ctx.newPage();
a.on("console", (m) => console.log("CONSOLE:", m.type(), m.text().slice(0, 200)));
a.on("pageerror", (e) => console.log("PAGEERROR:", String(e).slice(0, 300)));
await a.goto(BASE + "/admin/login", { waitUntil: "networkidle" });
await a.locator("#login-phone").fill("1157069732");
await a.locator("#login-password").fill("CambiaEstaClave2026!");
await a.getByRole("button", { name: /ingresar/i }).click();
await a.waitForURL("**/admin", { timeout: 45000 });
await a.goto(BASE + "/admin/usuarios", { waitUntil: "networkidle" });
const card = a.locator("div.rounded-xl", { hasText: "36017" });
console.log("cards:", await card.count());
await card.first().getByRole("button", { name: /aprobar/i }).click();
await a.getByRole("button", { name: /confirmar aprobaci/i }).waitFor();
await a.screenshot({ path: "dbg-antes.png" });
await a.getByRole("button", { name: /confirmar aprobaci/i }).click();
await a.waitForTimeout(6000);
await a.screenshot({ path: "dbg-despues.png" });
const body = await a.locator("body").innerText();
console.log("BODY HAS aprobado:", /aprobado como/i.test(body));
console.log("BODY HAS error:", /no tiene contrase|revis[aá]/i.test(body));
const m = body.match(/.{0,60}aprobado.{0,80}/i);
console.log("MATCH:", m ? m[0] : "(none)");
await browser.close();
